SachOnline/Controllers/SachOnlineController.cs
using System;
using System.Collections.Generic;
using System.Configuration.Provider;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;

namespace SachOnline.Controllers
{
    public class SachOnlineController : Controller
    {
        private string connection;
        private dbSachOnlineDataContext data;
        
        public SachOnlineController()
        {
            // Khởi tạo chuỗi kết nối
            connection = "Data Source=LAPTOP-SD6JFUCG\\MSSQLSERVER01;Initial Catalog=SachOnline;Integrated Security=True";
            data = new dbSachOnlineDataContext(connection);
        }

        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        // GET: SachOnline
        public ActionResult Index()
        {
            //Lay 6 quyen sach moi
            var listSachMoi = LaySachMoi(6);
            return View(listSachMoi);
        }
        
        public ActionResult SachBanNhieuPartial()
        {
            // Truy vấn cơ sở dữ liệu để lấy danh sách sách bán nhiều nhất.
            var listSachBanNhieu = data.SACHes.OrderByDescending(a => a.SoLuong).Take(6).ToList();

            // Trả về PartialView chứa danh sách sách bán nhiều nhất.
            return PartialView("SachBanNhieuPartial", listSachBanNhieu);
        }

        public ActionResult ChuDePartial()
        {
            var listChuDe = from cd in data.CHUDEs select cd;
            return PartialView(listChuDe);
        }
        public ActionResult NhaXuatBanPartial()
        {
            var listNhaXuatBan = from cd in data.NHAXUATBANs select cd;
            return PartialView(listNhaXuatBan);
        }

        // Lab3
        public ActionResult SachTheoChuDe(int id)
        {
            var sach = from s in data.SACHes where s.ChuDeID == id select s;
            return View(sach);
        }
        public ActionResult SachTheoNhaXuatBan(int id)
        {
            var sach = from s in data.SACHes where s.NhaXuatBanID == id select s;
            return View(sach);
        }
        public ActionResult ChiTietSach(int id)
        {
            var sach = from s in data.SACHes 
                       where s.SachID == id select s;
            return View(sach.Single());
        }
    }
}

SachOnline/Views/SachOnline/ChiTietSach.cshtml
@{
    ViewBag.Title = "ChiTietSach";
    Layout = "~/Views/Shared/_ LayoutUser.cshtml";
}
<style>
    .tensach {
        text-align: center;
        font-family: Tahoma;
        font-size: 22px;
        font-weight: bolder;
        text-transform: uppercase;
        height: 30px;
        padding: 25px 0px 50px 0px;
    }

    .anh {
        float: left;
        width: 350px;
        padding: 0px 20px;
    }
    .motasach {
        text-align: justify;
        padding-right: 50px;
        height: 280px;
        font-size: 17px;
    }
    .khoiA{
        float:right;
        padding:0px 80px;
        font-size:15px;
    }
</style>

<div class="thumbnail">
    <h4 class="tensach">@Model.TenSach</h4>
    <img style="height:400px;" class="anh" src="~/Images/@Model.AnhSp" alt="@Model.TenSach" />
    <div class="motasach">
        <p>
            @Html.Raw(Model.MoTa.ToString().Replace("\n", "</p><p>/&nbsp&nbsp&nbsp&nbsp&nbsp"))
        </p>
    </div>

    <div class="khoiA">
        <p class="ngaycapnhat"><b>Ngày cập nhật:</b> <i>@Html.FormatValue(@Model.NgayCapNhat, "{0:dd/MM/yyyy}")</i></p>
        <p class="giaban"><b>Giá bán:</b> <span style="color:blue; font-size:25px; font-family:Tahoma; font-style:italic; font-weight:800;">@Html.FormatValue(@Model.GiaBan, "{0:#,##0}")VNĐ</span></p>
        <p>
            <a href="@Url.Action("AddToCard","ShoppingCard") new {id = sach.SachID}" class="btn btn-primary" role="button">
                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
            </a>
        </p>
    </div>
</div>

SachOnline/Views/SachOnline/Index.cshtml
@model IEnumerable<SachOnline.Models.SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ LayoutUser.cshtml";
}
<hr>
<h2 class="text-center">SÁCH MỚI</h2>
<hr>

<div class="row text-center">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6 sp">
            <div class="thumbnail">
                <img src="~/Images/@sach.AnhSp" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook size">
                <div class="caption">
                    <h4 class="ten">
                        <a href="@Url.Action("ChiTietSach", "SachOnline", new { id = sach.SachID })">@sach.TenSach</a>
                    </h4>
                    <p>
                        <a href="@Url.Action("AddToCard","ShoppingCard") new {id = sach.SachID}" class="btn btn-primary" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

<nav class="text-center">
    <ul class="pagination">

        <li>
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>

        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>

        <li> 
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

SachOnline/Views/SachOnline/SachBanNhieuPartial.cshtml
@model IEnumerable<SachOnline.Models.SACH>

<hr>
<h2 class="text-center">SÁCH BÁN NHIỀU NHẤT</h2>
<hr>

<div class="book-slider-container">
    <button class="slider-button prev-button" id="prevButton"><i class="fa-solid fa-chevron-left"></i></button>
    <button class="slider-button next-button" id="nextButton"><i class="fa-solid fa-chevron-right"></i></button>
    <div class="book-slider">
        @foreach (var sach in Model)
        {
            <div class="book-slide">
                <div class="thumbnail">
                    <img src="~/Images/@sach.AnhSp" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook size" >
                    <div class="caption">
                        <h4 class="ten">
                            <a href="@Url.Action("ChiTietSach", "SachOnline", new { id = sach.SachID })">@sach.TenSach</a>
                        </h4>
                        <p>
                            <a href="@Url.Action("AddToCard","ShoppingCard") new {id = sach.SachID}" class="btn btn-primary" role="button">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<style>        
    .book-slider-container {
        overflow: hidden;
        position: center;
        width: 100%;
    }

    .book-slider {
        display: flex;
        overflow-x: hidden;
        scroll-behavior:unset;
        
    }

    .book-slide {
        flex: 0 0 33.3333%; /* Chia 3 cột cho mỗi slide */
        padding: 10px;
        /* Thêm kiểu dáng và khoảng cách cho từng cuốn sách */
    }

    .prev-button,
    .next-button {
        background-color: #fff;
        color: #000000;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
    }

    .prev-button {
        float: left;
    }

    .next-button {
        float: right;
    }
    .slider-button {
        height:540px;
    }
    .caption{
        text-align:center;
    }
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        var slider = $(".book-slider");
        var slideWidth = $(".book-slide").outerWidth();
        var scrollAmount = slideWidth * 1; // Di chuyển 1 cuốn sách mỗi lần

        $("#nextButton").click(function () {
            slider.animate({ scrollLeft: "+=" + scrollAmount }, 500);
        });

        $("#prevButton").click(function () {
            slider.animate({ scrollLeft: "-=" + scrollAmount }, 500);
        });
    });
</script>

SachOnline/Views/SachOnline/SachTheoChuDe.cshtml
@model IEnumerable<SachOnline.Models.SACH>
@{
    ViewBag.Title = "SachTheoChuDe";
    Layout = "~/Views/Shared/_ LayoutUser.cshtml";
}
<hr />
<h2 class="text-center">SÁCH THEO CHỦ ĐỀ</h2>
<hr />
<div class="row text-center">
    @foreach (var sach in Model)
    {
        <div class="book-slide">
            <div class="thumbnail">
                <img src="~/Images/@sach.AnhSp" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook size">
                <div class="caption">
                    <h4 class="ten">
                        <a href="@Url.Action("ChiTietSach", "SachOnline", new { id = sach.SachID })">@sach.TenSach</a>
                    </h4>
                    <p>
                        <a href="@Url.Action("AddToCard","ShoppingCard") new {id = sach.SachID}" class="btn btn-primary" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }

</div>

SachOnline/Views/SachOnline/SachTheoNhaXuatBan.cshtml
@model IEnumerable<SachOnline.Models.SACH>
@{
    ViewBag.Title = "SachTheoChuDe";
    Layout = "~/Views/Shared/_ LayoutUser.cshtml";
}
<hr />
<h2 class="text-center">SÁCH THEO NHÀ XUẤT BẢN</h2>
<hr />
<div class="row text-center">
    @foreach (var sach in Model)
    {
        <div class="book-slide">
            <div class="thumbnail">
                <img src="~/Images/@sach.AnhSp" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook size">
                <div class="caption">
                    <h4 class="ten">
                        <a href="@Url.Action("ChiTietSach", "SachOnline", new { id = sach.SachID })">@sach.TenSach</a>
                    </h4>
                    <p>
                        <a href="@Url.Action("AddToCard","ShoppingCard") new {id = sach.SachID}" class="btn btn-primary" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }

</div>